### PR TITLE
Implement the web micro-service

### LINKED ISSUE #4: Create web micro-service subcommand
YUP!

### PR DESCRIPTION
**Pull request by jampe**
Implement the web micro-service subcommand (fix #4)
- key has to be provided using --api <key> flag => consistent with the other commands
- web api provides the following endpoints:
  - GET /lookup/<hash> => does a hash lookup
  - POST /malware malware@file => does a scan (didn't solve the wait for the report problem tho)
- fixed scanfile returning a json string instead of the parsed object (I hope this won't break anything?).

### CODE REVIEW

**Comment by blacktop** [comment]
First of all...

yup

https://www.virustotal.com/en/documentation/private-api/#get-report

I guess the hash can be "An md5/sha1/sha256" so limiting to just sha1 is not complete.

and finally, I think in `web.md` the big JSON response goes with the lookup, not scan so I think the scan part should come after so people don't think that scanning will return results.

**Comment by blacktop** [comment]
I really appreciate your help.  I'm so used to people just being negative and only taking.  It is really refreshing to actually not only get help, but good help with things I don't have enough time to get around to.  

Thank you, thank you very much! :)

**Comment by jampe** [comment]
> First of all...
> 
> yup

No problem, thanks for all the work you've done ;)

> I guess the hash can be "An md5/sha1/sha256" so limiting to just sha1 is not complete.

Aight, makes sense. Fixed. I didn't check the VT api so I just assumed it'll work with sha1 only.

> and finally, I think in `web.md` the big JSON response goes with the lookup, not scan so I think the scan part should come after so people don't think that scanning will return results.

I tried to improve the documentation to make that clear. What do you think? :)

**Comment by blacktop** [comment]
lgtm! 👍

**Pull request merged**
